Temporary debug code #20

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,61 +42,106 @@ jobs:
         with:
           driver-opts: network=host
 
-      - name: Build and push to local registry
-        uses: docker/build-push-action@v5
-        with:
-          platforms: ${{ env.PLATFORMS }}
-          push: true
-          tags: localhost:5000/${{ secrets.DOCKERHUB_USERNAME }}/gnucash:github-ci
-          build-args: |
-            BASEIMAGE_VERSION=${{ env.BASEIMAGE_VERSION }}
-            GNUCASH_VERSION=${{ env.GNUCASH_VERSION }}
-
-      - name: Test image
-        run: |
-          platform_list="${{ env.PLATFORMS }}"
-          for platform in ${platform_list//,/ }
-          do
-            docker_image=localhost:5000/${{ secrets.DOCKERHUB_USERNAME }}/gnucash:github-ci
-            docker run --rm --platform ${platform} ${docker_image} sh -c 'echo Testing image on $(uname -m)...'
-            bats -j $(nproc) tests
-          done
-
+# r2r duplicated block - delete later
       - name: Login to Docker Hub
-        if: github.event_name != 'pull_request'
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ secrets.DOCKERHUB_USERNAME }}/gnucash
-          tags: |
-            type=raw,value=baseimage-gui-${{ env.BASEIMAGE_VERSION }}-gnucash-${{ env.GNUCASH_VERSION }},enable=${{ github.ref == 'refs/heads/main' }}
-            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
-            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
-            type=ref,event=tag
-            type=ref,event=pr
+      - name: Inspect
+        id: inspect
+        run: |
+          docker buildx imagetools inspect arturklauser/gnucash:latest
+          echo "raw=$(docker buildx imagetools inspect --raw arturklauser/gnucash:latest | tr -d '\n')" >> $GITHUB_OUTPUT
 
-      - name: Build and push to Dockerhub
-        if: github.event_name != 'pull_request'
-        uses: docker/build-push-action@v5
-        with:
-          platforms: ${{ env.PLATFORMS }}
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          build-args: |
-            BASEIMAGE_VERSION=${{ env.BASEIMAGE_VERSION }}
-            GNUCASH_VERSION=${{ env.GNUCASH_VERSION }}
+      - name: Debug workflow
+        run: |
+          # Get digest and architecture of each manifest in multi-platform image.
+          digests=(${{ join(fromJSON(steps.inspect.outputs.raw).manifests.*.digest, ' ') }})
+          architectures=(${{ join(fromJSON(steps.inspect.outputs.raw).manifests.*.platform.architecture, ' ') }})
+          if [[ "${#digests[@]}" -ne "${#architectures[@]}" ]]; then
+            echo "::error::Digest and arch array lengths do no match: [${architectures[@]}] [${digests[@]}]"
+            exit 1
+          fi
+          for ((i=0; i<${#digests[@]}; i++)); do
+            digest="${digests[i]}"
+            arch="${architectures[i]}"
+            echo "Architecture: ${arch}"
+            echo "Digest: ${digest}"
+            # The multi-platform docker image contains a bunch of manifests, but
+            # only the ones that have an valid architecture are manifests of
+            # platform sub-images we can actually run.
+            if [[ "${arch}" == 'unknown' ]]; then
+              echo '... skipping metadata image'
+              continue
+            fi
+            # Run the test suite.
+            export DOCKER_IMAGE=localhost:5000/${{ secrets.DOCKERHUB_USERNAME }}/gnucash:github-ci@${digest}
+            echo testing in $DOCKER_IMAGE
+          done
 
-      - name: Update Docker Hub description
-        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
-        uses: peter-evans/dockerhub-description@v4
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-          repository: ${{ secrets.DOCKERHUB_USERNAME }}/gnucash
-          readme-filepath: DOCKERHUB.md
+#            docker pull ${DOCKER_IMAGE}
+#            docker run --rm ${DOCKER_IMAGE} sh -c 'echo Testing image on $(uname -m)...'
+#            bats -j $(nproc) tests
+
+#
+#      - name: Build and push to local registry
+#        uses: docker/build-push-action@v5
+#        with:
+#          platforms: ${{ env.PLATFORMS }}
+#          push: true
+#          tags: localhost:5000/${{ secrets.DOCKERHUB_USERNAME }}/gnucash:github-ci
+#          build-args: |
+#            BASEIMAGE_VERSION=${{ env.BASEIMAGE_VERSION }}
+#            GNUCASH_VERSION=${{ env.GNUCASH_VERSION }}
+#
+#      - name: Test image
+#        run: |
+#          platform_list="${{ env.PLATFORMS }}"
+#          for platform in ${platform_list//,/ }
+#          do
+#            export DOCKER_IMAGE=localhost:5000/${{ secrets.DOCKERHUB_USERNAME }}/gnucash:github-ci
+#            docker pull --platform ${platform} ${DOCKER_IMAGE}
+#            docker run --rm --platform ${platform} ${DOCKER_IMAGE} sh -c 'echo Testing image on $(uname -m)...'
+#            bats -j $(nproc) tests
+#          done
+#
+#      - name: Login to Docker Hub
+#        if: github.event_name != 'pull_request'
+#        uses: docker/login-action@v3
+#        with:
+#          username: ${{ secrets.DOCKERHUB_USERNAME }}
+#          password: ${{ secrets.DOCKERHUB_TOKEN }}
+#
+#      - name: Docker meta
+#        id: meta
+#        uses: docker/metadata-action@v5
+#        with:
+#          images: ${{ secrets.DOCKERHUB_USERNAME }}/gnucash
+#          tags: |
+#            type=raw,value=baseimage-gui-${{ env.BASEIMAGE_VERSION }}-gnucash-${{ env.GNUCASH_VERSION }},enable=${{ github.ref == 'refs/heads/main' }}
+#            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
+#            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
+#            type=ref,event=tag
+#            type=ref,event=pr
+#
+#      - name: Build and push to Dockerhub
+#        if: github.event_name != 'pull_request'
+#        uses: docker/build-push-action@v5
+#        with:
+#          platforms: ${{ env.PLATFORMS }}
+#          push: true
+#          tags: ${{ steps.meta.outputs.tags }}
+#          build-args: |
+#            BASEIMAGE_VERSION=${{ env.BASEIMAGE_VERSION }}
+#            GNUCASH_VERSION=${{ env.GNUCASH_VERSION }}
+#
+#      - name: Update Docker Hub description
+#        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
+#        uses: peter-evans/dockerhub-description@v4
+#        with:
+#          username: ${{ secrets.DOCKERHUB_USERNAME }}
+#          password: ${{ secrets.DOCKERHUB_TOKEN }}
+#          repository: ${{ secrets.DOCKERHUB_USERNAME }}/gnucash
+#          readme-filepath: DOCKERHUB.md
