Add docker image testing
Add docker image testing

This change adds a testing framework for the Docker image build process to
prevent broken images from being published. The implementation follows the
testing framework of the jlesage/docker-baseimage-gui repository and reuses some
of it's setup/teardown BATS code.
* An image is built for all architectures and pushed to a local temporary registry.
* Tests run on all architectures that the image was built for.
* If all tests pass on all architectures, the image is rebuilt and pushed to dockerhub.
  * This is required because of a docker limitation that doesn't allow a multi-platform
     image from being "pulled" from a repository to the local docker daemon to then
     push it to another repository. Rebuilding should be fast though due to layer caching
     in the local docker daemon.

A simple test case has been added to verify that the `gnucash` process is running in
the container after startup.

Fixes #17

---------

Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Build and Push Docker Image
+name: Docker Gnucash CI/CD
 
 on:
   push:
@@ -10,21 +10,83 @@ on:
     branches:
       - 'main'
 
+env:
+  BASEIMAGE_VERSION: ubuntu-24.04-v4
+  GNUCASH_VERSION: 5.13
+  PLATFORMS: linux/amd64,linux/arm64
+  DOCKER_IMAGE_NAME: arturklauser/gnucash
+
 jobs:
   build:
     runs-on: ubuntu-latest
-    env:
-      BASEIMAGE_VERSION: ubuntu-24.04-v4
-      GNUCASH_VERSION: 5.13
+    services:
+      registry:
+        image: registry:2
+        ports:
+          - 5000:5000
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Setup BATS
+        uses: mig4/setup-bats@v1
+        with:
+          bats-version: 1.13.0
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
+        with:
+          platforms: ${{ env.PLATFORMS }}
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+        with:
+          driver-opts: network=host
+
+      - name: Build and push to local registry
+        uses: docker/build-push-action@v5
+        with:
+          platforms: ${{ env.PLATFORMS }}
+          push: true
+          tags: localhost:5000/${{ env.DOCKER_IMAGE_NAME }}:github-ci
+          build-args: |
+            BASEIMAGE_VERSION=${{ env.BASEIMAGE_VERSION }}
+            GNUCASH_VERSION=${{ env.GNUCASH_VERSION }}
+
+      - name: Inspect
+        id: inspect
+        run: |
+          docker buildx imagetools inspect localhost:5000/${{ env.DOCKER_IMAGE_NAME }}:github-ci
+          echo "raw=$(docker buildx imagetools inspect --raw localhost:5000/${{ env.DOCKER_IMAGE_NAME }}:github-ci | tr -d '\n')" >> $GITHUB_OUTPUT
+
+      - name: Test image
+        run: |
+          # Get digest and architecture of each manifest in multi-platform image.
+          digests=(${{ join(fromJSON(steps.inspect.outputs.raw).manifests.*.digest, ' ') }})
+          architectures=(${{ join(fromJSON(steps.inspect.outputs.raw).manifests.*.platform.architecture, ' ') }})
+          if [[ "${#digests[@]}" -ne "${#architectures[@]}" ]]; then
+            echo "::error::Digest and arch array lengths do no match: [${architectures[@]}] [${digests[@]}]"
+            exit 1
+          fi
+          for ((i=0; i<${#digests[@]}; i++)); do
+            digest="${digests[i]}"
+            arch="${architectures[i]}"
+            echo "Digest: ${digest}"
+            echo "Architecture: ${arch}"
+            # The multi-platform docker image contains a bunch of manifests, but
+            # only the ones that have an valid architecture are manifests of
+            # platform sub-images we can actually run.
+            if [[ "${arch}" == 'unknown' ]]; then
+              echo '... skipping metadata image'
+              continue
+            fi
+            # Run the test suite on one architecture.
+            export DOCKER_IMAGE=localhost:5000/${{ env.DOCKER_IMAGE_NAME }}:github-ci@${digest}
+            echo "Running tests on image ${DOCKER_IMAGE}..."
+            docker pull ${DOCKER_IMAGE}
+            docker run --rm ${DOCKER_IMAGE} sh -c 'echo Testing image on $(uname -m)...'
+            bats -j $(nproc) tests
+          done
 
       - name: Login to Docker Hub
         if: github.event_name != 'pull_request'
@@ -37,7 +99,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ${{ secrets.DOCKERHUB_USERNAME }}/gnucash
+          images: ${{ env.DOCKER_IMAGE_NAME }}
           tags: |
             type=raw,value=baseimage-gui-${{ env.BASEIMAGE_VERSION }}-gnucash-${{ env.GNUCASH_VERSION }},enable=${{ github.ref == 'refs/heads/main' }}
             type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
@@ -45,14 +107,13 @@ jobs:
             type=ref,event=tag
             type=ref,event=pr
 
-      - name: Build and push
+      - name: Build and push to Dockerhub
+        if: github.event_name != 'pull_request'
         uses: docker/build-push-action@v5
         with:
-          context: .
-          platforms: linux/amd64,linux/arm64
-          push: ${{ github.event_name != 'pull_request' }}
+          platforms: ${{ env.PLATFORMS }}
+          push: true
           tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
           build-args: |
             BASEIMAGE_VERSION=${{ env.BASEIMAGE_VERSION }}
             GNUCASH_VERSION=${{ env.GNUCASH_VERSION }}
@@ -63,5 +124,5 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-          repository: ${{ secrets.DOCKERHUB_USERNAME }}/gnucash
+          repository: ${{ env.DOCKER_IMAGE_NAME }}
           readme-filepath: DOCKERHUB.md
